#!/bin/bash

home_dir="/home/$(whoami)"

stamp="GARBAGE"
ar_dir="$home_dir/.archive"

# 1GB
limit_size=1000000
# 10GB
#limit_size=10000000
# 100GB
#limit_size=100000000

local_conf="$home_dir/.garbage-conf"
[[ -f "$local_conf" ]] && . "$local_conf"
