#!/bin/bash

target="${1:-.}"

bin_dir="$(dirname "$0")"
. "$bin_dir/garbage-conf"

cur_size="$(du -s "$target" | awk '{print $1}')"
if [[ "$cur_size" -gt "$limit_size" ]]
then
    find $target -type f -printf '%C@ %p\0' | sort -z -k 1 -n |
        while read -d $'\0' garbage
            do
                timestamp="$(echo "$garbage" | cut -d ' ' -f 1)"
                path="$(echo "$garbage" | cut -d ' ' -f 2-)"
                [[ "$timestamp" -lt "$(date --date=yesterday +'%s')" ]] && break
                rm "$path"
                cur_size="$(du -s "$target" | awk '{print $1}')"
                [[ "$cur_size" -lt "$limit_size" ]] && break
            done
fi

find "$target" -type d -empty -exec rmdir {} \;
